language: node_js
node_js:  
  - "v9.2.0"

before_script:
   - npm i

jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test-ci
    - stage: deploy to production
      script: skip
      deploy: &heroku
        provider: heroku
        app: rd-shiryu
        api_key: $HEROKU_API_KEY
      if: branch = master
